[package]
name = "usufruct"
edition = "2024"
license = "Apache-2.0"
authors = ["Antonio Jiménez <build@0xkurious.xyz>"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
usufruct = "0x0"
