// Copyright (c) 2026 Antonio Jiménez
// SPDX-License-Identifier: Apache-2.0

// Cross-block deferred initialization requires `mut` even for single-assignment
// variables. Move's compiler warns W09012 (unused_mut) in these cases — suppressed
// because the mut is syntactically required, not stylistically optional.
#[allow(unused_let_mut)]
#[test_only]
module usufruct::fee_inbox_tests;

use std::unit_test::assert_eq;
use sui::{
    balance,
    clock,
    coin,
    event,
    sui::SUI,
    test_scenario::{Self, Scenario},
};
use usufruct::{
    commitment_policy,
    escrow::{Self, Escrow},
    escrow_corpus,
    fee_inbox,
    fee_message::{Self, FeeMessage, FeeMessageSent},
    owner_cap,
    phases,
    protocol_fee_inbox::{Self, ProtocolFeeInbox},
    protocol_fee_ref::ProtocolFeeRef,
    refund_address,
    tenant_cap,
    tenant_seat,
};

// ─── Fixtures ──────────────────────────────────────────────────────────────────

const OWNER:   address = @0x07;
const TENANT:  address = @0xA1;
const STAKE:   u64     = 1_000_000_000;   // 1 SUI
const CEILING: u64     = 100_000;

public struct DemoAsset has key, store { id: UID }

fun mk_demo_asset(ctx: &mut TxContext): DemoAsset {
    DemoAsset { id: object::new(ctx) }
}

fun mk_tenant_seat(stake: u64): tenant_seat::TenantSeat<SUI> {
    tenant_seat::new(
        tenant_cap::from_id(object::id_from_address(@0xCA1)),
        refund_address::new(TENANT),
        balance::create_for_testing<SUI>(stake),
    )
}

fun setup(): Scenario {
    let mut sc = test_scenario::begin(@0x0);
    sc.next_tx(OWNER);
    { protocol_fee_inbox::init_for_testing(sc.ctx()); };
    sc
}

// ─── FI — fee_inbox::inbox_id ──────────────────────────────────────────────────

// FI1: inbox_id extracts the fee inbox ID from a ProtocolFeeRef.
#[test]
fun fi1_inbox_id_returns_inbox_id() {
    let mut sc = setup();
    sc.next_tx(OWNER);
    {
        let fee_ref   = sc.take_immutable<ProtocolFeeRef>();
        let inbox     = sc.take_from_sender<ProtocolFeeInbox>();
        let inbox_id  = object::id(&inbox);

        assert_eq!(fee_inbox::inbox_id(&fee_ref), inbox_id);

        sc.return_to_sender(inbox);
        test_scenario::return_immutable(fee_ref);
    };
    sc.end();
}

// ─── FC — fee_inbox::collect_fee_messages ──────────────────────────────────────

// FC1: empty ticket vector returns zero coin.
#[test]
fun fc1_collect_empty_vector_returns_zero_coin() {
    let mut sc = setup();
    sc.next_tx(OWNER);
    {
        let mut inbox = sc.take_from_sender<ProtocolFeeInbox>();
        let coin      = fee_inbox::collect_fee_messages<SUI>(&mut inbox, vector[], sc.ctx());
        assert_eq!(coin::value(&coin), 0);
        transfer::public_transfer(coin, OWNER);
        sc.return_to_sender(inbox);
    };
    sc.end();
}

// FC2: FeeMessages generated by a real tenure expiry are drained correctly.
// Flow: integrate → drive_to_rented (inject tenant stake) →
//       fire_do_tenure_expiry (posts FeeMessage) → collect via fee_inbox API.
#[test]
fun fc2_collect_protocol_fees_from_real_tenure_expiry() {
    let mut sc = setup();

    // --- Block 1: integrate the asset ---
    sc.next_tx(OWNER);
    let ensemble  = escrow_corpus::by_tag(0); // handover=off, descent=off, immediate commitment
    let fee_ref   = sc.take_immutable<ProtocolFeeRef>();
    let clk       = clock::create_for_testing(sc.ctx());
    let asset     = mk_demo_asset(sc.ctx());
    let owner_cap = escrow::integrate<DemoAsset, SUI>(
        asset, ensemble, commitment_policy::new_immediate(), &fee_ref, &clk, sc.ctx(),
    );
    let escrow_id = owner_cap::proj_escrow_id(&owner_cap);
    test_scenario::return_immutable(fee_ref);
    clock::destroy_for_testing(clk);

    // --- Block 2: inject tenant and drive to rented, then expire the tenure ---
    let mut msg_id: ID;
    sc.next_tx(OWNER);
    {
        let mut escrow = sc.take_shared_by_id<Escrow<DemoAsset, SUI>>(escrow_id);
        escrow::drive_to_rented_for_testing(&mut escrow, mk_tenant_seat(STAKE), 0);
        let boundary = phases::timestamp(CEILING);
        escrow::fire_do_tenure_expiry_for_testing(&mut escrow, boundary, sc.ctx());

        // FeeMessageSent is emitted in this tx; capture msg_id for receipt in next block.
        let sent = event::events_by_type<FeeMessageSent<SUI>>();
        assert!(sent.length() > 0, 0);
        msg_id = fee_message::sent_fee_message_id(&sent[0]);

        test_scenario::return_shared(escrow);
    };

    // --- Block 3: collect the fee message via the public API ---
    sc.next_tx(OWNER);
    {
        let mut inbox = sc.take_from_sender<ProtocolFeeInbox>();
        let ticket    = test_scenario::receiving_ticket_by_id<FeeMessage<SUI>>(msg_id);
        let coin      = fee_inbox::collect_fee_messages<SUI>(&mut inbox, vector[ticket], sc.ctx());

        assert!(coin::value(&coin) > 0, 1);

        transfer::public_transfer(coin, OWNER);
        sc.return_to_sender(inbox);
    };

    owner_cap::burn(owner_cap, OWNER);
    sc.end();
}

// FC3: coin value from collect equals the fee from the FeeMessageSent event.
#[test]
fun fc3_collected_coin_value_matches_sent_amount() {
    let mut sc = setup();

    sc.next_tx(OWNER);
    let ensemble  = escrow_corpus::by_tag(0);
    let fee_ref   = sc.take_immutable<ProtocolFeeRef>();
    let clk       = clock::create_for_testing(sc.ctx());
    let asset     = mk_demo_asset(sc.ctx());
    let owner_cap = escrow::integrate<DemoAsset, SUI>(
        asset, ensemble, commitment_policy::new_immediate(), &fee_ref, &clk, sc.ctx(),
    );
    let escrow_id = owner_cap::proj_escrow_id(&owner_cap);
    test_scenario::return_immutable(fee_ref);
    clock::destroy_for_testing(clk);

    let mut msg_id:    ID;
    let mut fee_amount: u64;
    sc.next_tx(OWNER);
    {
        let mut escrow = sc.take_shared_by_id<Escrow<DemoAsset, SUI>>(escrow_id);
        escrow::drive_to_rented_for_testing(&mut escrow, mk_tenant_seat(STAKE), 0);
        escrow::fire_do_tenure_expiry_for_testing(&mut escrow, phases::timestamp(CEILING), sc.ctx());

        let sent  = event::events_by_type<FeeMessageSent<SUI>>();
        msg_id    = fee_message::sent_fee_message_id(&sent[0]);
        fee_amount = fee_message::sent_amount(&sent[0]);

        test_scenario::return_shared(escrow);
    };

    sc.next_tx(OWNER);
    {
        let mut inbox = sc.take_from_sender<ProtocolFeeInbox>();
        let ticket    = test_scenario::receiving_ticket_by_id<FeeMessage<SUI>>(msg_id);
        let coin      = fee_inbox::collect_fee_messages<SUI>(&mut inbox, vector[ticket], sc.ctx());

        assert_eq!(coin::value(&coin), fee_amount);

        transfer::public_transfer(coin, OWNER);
        sc.return_to_sender(inbox);
    };

    owner_cap::burn(owner_cap, OWNER);
    sc.end();
}
